import pathlib
p = pathlib.Path("README.md")
s = p.read_text(encoding="utf-8-sig")
def sub(old, new):
    global s
    if s.count(old) != 1:
        raise SystemExit("anchor %d times: %r" % (s.count(old), old[:60]))
    s = s.replace(old, new)

sub("""At rpm 5000, throttle 80 %, altitude 6000 ft, OAT 10 C the twin must return
`anomaly_probability = 0.5443998040908319` exactly. Any change to the adapter,
deck, baselines or residual calculation that moves this number is a regression
until proven otherwise.""",
"""At rpm 5000, throttle 80 %, altitude 6000 ft, OAT 10 C the twin must return
`anomaly_probability = 0.3702002297327016` on the MVEM healthy cruise frame
(fuelflow 16.4472, coolant 88.0, EGT 740.96, oil pressure 3.168, oil temp 90.0).
The zero-residual harness value, where measured is set equal to expected, is
`0.36390550779530195` - owned by `shared/stress_sim.HEALTHY_P_ANOM` and asserted
by both `fault_injection` CASE 0 and `throttle_dynamics` CASE 1. Any change to
the adapter, deck, baselines or residual calculation that moves either number is
a regression until proven otherwise.

Both were previously `0.5443998040908319`. That value predates the MVEM refit
and is dead.""")

sub("""The anomaly gate threshold of 0.65 is untrusted pre-retrain, and the gate was
measured non-monotonic and direction-blind - coolant crosses at +0.038 C but
-10 C does not cross at all, and oil pressure never crosses in either direction.
The multiclass label `fuel_pressure_dev` is a dead class and is never predicted,
so a genuine fuel pressure deviation cannot be diagnosed. RUL is emitted with
`rul_trusted = False` and `rul_units = 'unknown'`; treat it as an ordering, not
a time. Transient frames are not scored by design and surface as `UNAVAILABLE`
with a reason, which costs roughly 100 s of settling after a throttle step. The
deck accepts throttle only in [56.5, 100] % and ambient only in
[-27.98, 30] C, so idle, low cruise and hot days are refused rather than scored.

Training data is Cantera-generated from limited public Rotax 915 iS figures and
is estimated ~70 % faithful. AERIS demonstrates the detection architecture, not
certified thresholds.""",
"""The anomaly gate decides at 0.50, re-derived on held-out validation engines and
owned by `confidence_threshold` in `models/configs/reconstruction_config.json`.
Measured on 10 held-out engines: F1 0.907, ROC-AUC 0.985, false-alarm rate
0.74 %. Four of five fault classes are detected above 0.998.
`cooling_degradation` is the weak class at 0.19: the engine is thermostatted, so
a failing coolant pump is invisible at low load and only becomes observable
under thermal load. Fixing it needs a coolant delta-T channel
(`coolant_temp_in_c` minus `coolant_temp_out_c`), which is a contract change.

Single-cylinder misfire cannot be distinguished from a uniform fuel-pressure
deviation, and this is an instrumentation limit rather than a model weakness.
One cylinder at 0.62 fuel trim delivers 0.905 of nominal fuel flow; a uniform
trim of 0.905 is `fuel_pressure_dev` at frac 0.59. MVEM reports one MEAN EGT
across four cylinders and no crank-speed irregularity, so the two faults are the
same point in the measured space. Detection is reliable (0.9999); the type
assignment is not. Present either as "fuel/combustion fault, type uncertain".

Fuel flow alone is not a detection channel: +/-1.5 kg/h on a 16.45 kg/h nominal
scores 0.0034 and 0.0845, and bisection finds no crossing in either direction.

RUL is emitted with `rul_trusted = False` and `rul_units = 'unknown'` (R2
-0.103); treat it as an ordering, not a time. It does not respond to the fault
the gate is most confident about - a severe lubrication injection scoring 0.9999
moves `rul_raw` from 180.2 to 179.7.

Transient frames are not scored by design and surface as `UNAVAILABLE` with a
reason, which costs roughly 100 s of settling after a throttle step. The deck
accepts throttle in [20, 100] %, altitude in [0, 22800] ft and ambient in
[-39.5, 39.86] C, taken from the healthy rows the baselines were fit on.

Training data is generated by a mean-value engine model
(`shared/engine_mvem.py`), calibrated to manufacturer figures at 5800 rpm WOT
sea level - fuel 33.8 L/h, 104.4 kW, BSFC 243 g/kWh, all matching to 0.0 %.
NO OTHER POINT IN THE ENVELOPE IS VALIDATED; no public part-throttle or altitude
test data exists for the Rotax 915 iS. Dataset `mvem_v3.parquet`, 629,441 rows,
60 virtual engines. AERIS demonstrates the detection architecture, not certified
thresholds.

The previous version of this section described a gate measured non-monotonic and
direction-blind, a dead `fuel_pressure_dev` class, and an oil pressure loss that
could not be detected. All four were artifacts of one serving bug:
`residual_calc` applied `abs()` per channel while the gate trains on signed
deltas, so a 0.91 bar pressure COLLAPSE arrived as +0.91 and scored HEALTHY.
Fixed in e49cf96.""")

sub("""`residuals` are unsigned - do not infer direction from them. `headline` already
contains "(unvalidated)".""",
"""`residuals` are SIGNED (`measured - expected`) as of e49cf96 - a UI may and
should read direction from the sign. They were previously served as magnitudes.
`headline` already contains "(unvalidated)".""")

sub("""SHAP attributions over a gate that measures at chance explain the model, not
the engine.""",
"""SHAP attributions explain the model, not the engine. Note `shap` imports
`numba`, which loads a native DLL that Windows Application Control may block;
set `AERIS_EXPLAIN=0` to boot without explanations if startup fails on it.""")

sub("""Every frame response embeds a `caveats` block with measured model metrics: gate
precision 0.511 / recall 0.9982 / F1 0.676 (equals the always-fault baseline at
a 0.511 prior), RUL R2 -0.103 / MAE 107.""",
"""Every frame response embeds a `caveats` block with measured model metrics: gate
precision 0.927 / recall 0.888 / F1 0.907 / ROC-AUC 0.985, multiclass accuracy
0.912, RUL R2 -0.103 / MAE 107.""")

p.write_text(s, encoding="utf-8")
print("README updated")

q = pathlib.Path("static/index.html")
h = q.read_text(encoding="utf-8-sig")
old = """<div id="untrusted">MODELS UNTRUSTED &mdash; gate F1 0.676 = trivial baseline
  &middot; RUL R&sup2; &minus;0.103 &middot; placeholder models, plumbing
  verified. Nothing here is airworthiness evidence.</div>"""
new = """<div id="untrusted">MODELS UNVALIDATED &mdash; gate F1 0.907 / ROC-AUC 0.985 on
  held-out engines &middot; RUL R&sup2; &minus;0.103, ordering only
  &middot; cooling_degradation 0.19 weak class &middot; synthetic MVEM data,
  one validated operating point. Nothing here is airworthiness evidence.</div>"""
if h.count(old) != 1:
    print("WARN banner anchor %d times -- edit static/index.html by hand" % h.count(old))
else:
    q.write_text(h.replace(old, new), encoding="utf-8")
    print("banner updated")
